In [71]:
import numpy as np

In [72]:
def LDU(A: np.ndarray):
    """PA = LDU decomposition algorithm

    Args:
        A (np.ndarray): input array of shape (m, n) where m >= n and A is of rank n

    Returns:
        P (np.ndarray): permutation matrix
        L (np.ndarray): lower triangular matrix
        D (np.ndarray): diagonal matrix
        U (np.ndarray): upper triangular matrix
    """

    # const A
    A = A.copy().astype(float)
    print("input matrix A:\n", A, end="\n\n")

    # verify the input matrix A is valid for LDU decomposition
    assert len(A.shape) == 2, "Input matrix A must be a 2D array"

    n_row, n_col = A.shape
    print("Input matrix A is a {}x{} matrix\n".format(n_row, n_col))

    assert n_row >= n_col, "Input matrix A must have more rows than columns"
    assert np.linalg.matrix_rank(A) == n_col, "Input matrix A must be of full rank"

    # initialize the permutation matrix P, lower triangular matrix L, diagonal matrix D, and upper triangular matrix U
    P = np.eye(n_row, dtype=float)
    L = np.eye(n_row, dtype=float)
    D = np.eye(n_row, dtype=float)
    U = np.zeros((n_row, n_col), dtype=float)

    # solve for PA = LA'
    print("\nSolve for PA = LA':\n")
    A_prime = A.copy()
    for col in range(n_col):
        if A_prime[col, col] == 0:
            if np.max(A_prime[col:, col]) == 0:
                # Should not happen since A is of full rank
                continue
            # find the row with the largest absolute value in the current column
            max_row = np.argmax(np.abs(A_prime[col:, col])) + col
            print("switching row", col + 1, "with row", max_row + 1)
            # swap the current row with the row of the largest value in the current column
            P[[col, max_row]] = P[[max_row, col]]
            A_prime[[col, max_row]] = A_prime[[max_row, col]]
        for row in range(col + 1, n_row):
            L[row, col] = A_prime[row, col] / A_prime[col, col]
            A_prime[row] -= L[row, col] * A_prime[col]

        print(
            "After eliminating column",
            col + 1,
            ":\nP:\n",
            P,
            "\nL:\n",
            L,
            "\nA':\n",
            A_prime,
            end="\n\n",
        )

    print("After solving PA = LA'\nP:\n", P, "\nL:\n", L, "\nA':\n", A_prime)
    print("PA =\n", P @ A, "\nLA' =\n", L @ A_prime, end="\n\n")

    # Solve for A' = DU
    print("\nSolve for A' = DU:\n")
    for row in range(n_col):
        D[row, row] = A_prime[row, row]
        U[row] = A_prime[row] / D[row, row]
        print(
            "After eliminating row",
            row + 1,
            ":\nD:\n",
            D,
            "\nU:\n",
            U,
            end="\n\n",
        )

    print("After solving A' = DU\nD:\n", D, "\nU:\n", U)
    print("A'=\n", A_prime, "\nDU =\n", D @ U)

    # Check if the decomposition is correct
    assert np.array_equal(P @ A, L @ D @ U), "Decomposition is incorrect"

    # Print the final result
    print("\nFinal result:", "\nP:\n", P, "\nL:\n", L, "\nD:\n", D, "\nU:\n", U)

    return P, L, D, U

In [73]:
A1 = np.array([[10, -10, 0], [0, -4, 2], [2, 0, -5]])
A2 = np.array([[5, -5, 0, 0], [5, 5, 5, 0], [0, -1, 4, 1], [0, 4, -1, 2], [0, 0, 2, 1]])
A3 = np.array([[1, 1, 1], [10, 2, 9], [8, 0, 7]])

In [74]:
P1, L1, D1, U1 = LDU(A1)

input matrix A:
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  2.   0.  -5.]]

Input matrix A is a 3x3 matrix


Solve for PA = LA':

After eliminating column 1 :
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[1.  0.  0. ]
 [0.  1.  0. ]
 [0.2 0.  1. ]] 
A':
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  0.   2.  -5.]]

After eliminating column 2 :
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.2 -0.5  1. ]] 
A':
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  0.   0.  -4.]]

After eliminating column 3 :
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.2 -0.5  1. ]] 
A':
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  0.   0.  -4.]]

After solving PA = LA'
P:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
L:
 [[ 1.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.2 -0.5  1. ]] 
A':
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  0.   0.  -4.]]
PA =
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  2.   0.  -5.]] 
LA' =
 [[ 10. -10.   0.]
 [  0.  -4.   2.]
 [  2.   0.  -5.

In [75]:
P2, L2, D2, U2 = LDU(A2)

input matrix A:
 [[ 5. -5.  0.  0.]
 [ 5.  5.  5.  0.]
 [ 0. -1.  4.  1.]
 [ 0.  4. -1.  2.]
 [ 0.  0.  2.  1.]]

Input matrix A is a 5x4 matrix


Solve for PA = LA':

After eliminating column 1 :
P:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
L:
 [[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
A':
 [[ 5. -5.  0.  0.]
 [ 0. 10.  5.  0.]
 [ 0. -1.  4.  1.]
 [ 0.  4. -1.  2.]
 [ 0.  0.  2.  1.]]

After eliminating column 2 :
P:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 
L:
 [[ 1.   0.   0.   0.   0. ]
 [ 1.   1.   0.   0.   0. ]
 [ 0.  -0.1  1.   0.   0. ]
 [ 0.   0.4  0.   1.   0. ]
 [ 0.   0.   0.   0.   1. ]] 
A':
 [[ 5.  -5.   0.   0. ]
 [ 0.  10.   5.   0. ]
 [ 0.   0.   4.5  1. ]
 [ 0.   0.  -3.   2. ]
 [ 0.   0.   2.   1. ]]

After eliminating column 3 :
P:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 

In [76]:
P3, L3, D3, U3 = LDU(A3)

input matrix A:
 [[ 1.  1.  1.]
 [10.  2.  9.]
 [ 8.  0.  7.]]

Input matrix A is a 3x3 matrix



AssertionError: Input matrix A must be of full rank