In [21]:
import numpy as np

# Question 2
Compute the PA = LDU decomposition and the SVD decomposition for each of the following matrices: (In fact, here it is enough to let P be an identity matrix, so A = LDU.)

You may use any method or tools you wish to solve this problem, including pre-defined routines from MatLab or Python,
your code, and/or hand calculations. (Hand calculations may be easiest for computing the P A = LDU decompositions
of these examples. We recommend using pre-defined code to compute the SVD decompositions.)
Show how you obtained your solutions, that is, show your work, including intermediate steps.

In [22]:
A1 = np.array([[10, -10, 0], [0, -4, 2], [2, 0, -5]])
A2 = np.array([[5, -5, 0, 0], [5, 5, 5, 0], [0, -1, 4, 1], [0, 4, -1, 2], [0, 0, 2, 1]])
A3 = np.array([[1, 1, 1], [10, 2, 9], [8, 0, 7]])

In [23]:
U1, Sigma1, Vt1 = np.linalg.svd(A1, full_matrices=True)
print("U:\n", U1, "\nSigma:\n", Sigma1, "\nVt:\n", Vt1)

U:
 [[-0.97502551  0.01928246 -0.22125424]
 [-0.19998937 -0.50949125  0.83691273]
 [-0.09658937  0.86025976  0.50062326]] 
Sigma:
 [14.49778417  5.94733738  1.85564877] 
Vt:
 [[-0.68585887  0.72771207  0.00572281]
 [ 0.3217144   0.31024647 -0.89456524]
 [-0.65276141 -0.61170439 -0.44690075]]


In [24]:
U2, Sigma2, Vt2 = np.linalg.svd(A2)
print("U:\n", U2, "\nSigma:\n", Sigma2, "\nVt:\n", Vt2)

U:
 [[ 0.1126266   0.86708016  0.37480574 -0.30750061 -0.0212435 ]
 [-0.93215705  0.15225202  0.1626033   0.2846251   0.0212435 ]
 [-0.20196646  0.2257811  -0.74973268 -0.31691184 -0.4956816 ]
 [-0.2398716  -0.41225956  0.38334628 -0.77085017 -0.17702914]
 [-0.14166742  0.06368894 -0.35217519 -0.36026217  0.84973988]] 
Sigma:
 [9.14492811 7.79814769 4.42070712 2.23976139] 
Vt:
 [[-0.44807922 -0.65407164 -0.60275097 -0.09003647]
 [ 0.65357327 -0.69875055  0.28263403 -0.06861233]
 [ 0.60783153  0.27645026 -0.74051747 -0.07582844]
 [-0.05106685  0.08667875  0.09188657 -0.99067443]]


In [25]:
U3, Sigma3, Vt3 = np.linalg.svd(A3)
print("U:\n", U3, "\nSigma:\n", Sigma3, "\nVt:\n", Vt3)

U:
 [[-0.08686637 -0.57077804 -0.81649658]
 [-0.78592384 -0.4643889   0.40824829]
 [-0.6121911   0.67716718 -0.40824829]] 
Sigma:
 [1.72832333e+01 1.51322343e+00 2.25035269e-15] 
Vt:
 [[-0.74312678 -0.09597244 -0.66223249]
 [ 0.1339329  -0.99096789 -0.0066797 ]
 [ 0.65561007  0.09365858 -0.74926865]]


# Question 3
Solve the systems of equations Ax = b for the values of A and b given below. For each system, specify whether the system has zero, one, or many exact solutions. If a system has zero exact solutions, give “the SVD solution” (as defined in class) and explain what this solution means. If a system has a unique exact solution, compute that solution. If a system has more than one exact solution, specify both “the SVD solution” and all solutions, using properties of the SVD decomposition of the matrix A, as discussed in class.
Show your work, including verifying that your answers are correct.

Parts (b) and (c) have the same A matrix but different b vectors. You will see that “the SVD solution” is the same for
both parts. Explain why that makes sense. Your explanation should be based on the meaning of the columns of U that
arose in A’s SVD decomposition.

In [26]:
def solve_systems_of_equations(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Solve a system of equations of the form Ax = b for x.

    Args:
        A (np.ndarray): Input matrix A
        b (np.ndarray): Target vector b

    Returns:
        np.ndarray: Solution vector x
    """

    # copy A and b to avoid modifying the original matrices
    A = A.copy()
    b = b.copy()

    # reshape b into a column vector
    b = b.reshape(-1, 1)

    # verify that b has the same number of rows as A
    assert A.shape[0] == b.shape[0], "A and b have different numbers of rows"

    # perform SVD on A
    U, Sigma, Vt = np.linalg.svd(A)

    # factor out extremely small singular values of Sigma
    Sigma = Sigma[Sigma > 1e-10]

    # construct the pseudo-inverse of A
    M_sigma_inverse = np.zeros((U.shape[1], Vt.shape[0]))
    for i in range(len(Sigma)):
        M_sigma_inverse[i][i] = 1 / Sigma[i]
    M_pseudo_inverse = Vt.T @ M_sigma_inverse @ U.T
    print("pseudo inverse of matrix A:\n", M_pseudo_inverse)

    # compute the "solution" to the system of equations
    x = M_pseudo_inverse @ b
    return x

In [27]:
solve_systems_of_equations(A1, np.array([10, 2, 13]))

pseudo inverse of matrix A:
 [[ 0.125  -0.3125 -0.125 ]
 [ 0.025  -0.3125 -0.125 ]
 [ 0.05   -0.125  -0.25  ]]


array([[-1.],
       [-2.],
       [-3.]])

In [28]:
x_bar = solve_systems_of_equations(A3, np.array([1, 3, 1]))

pseudo inverse of matrix A:
 [[-0.04678363 -0.00730994  0.08625731]
 [ 0.37426901  0.30847953 -0.44005848]
 [ 0.00584795  0.03216374  0.02046784]]


In [29]:
x_bar
A3 @ x_bar

array([[1.],
       [3.],
       [1.]])

In [30]:
x_bar = solve_systems_of_equations(A3, np.array([3, 2, 2]))

pseudo inverse of matrix A:
 [[-0.04678363 -0.00730994  0.08625731]
 [ 0.37426901  0.30847953 -0.44005848]
 [ 0.00584795  0.03216374  0.02046784]]


In [31]:
x_bar
A3 @ x_bar

array([[1.],
       [3.],
       [1.]])